version: '3.8'

services:
  scylladb:
    build: .
    container_name: some-scylla
    hostname: some-scylla
    ports:
      - "9042:9042"
    command: ["--smp", "1", "--memory", "750M", "--overprovisioned", "1"]
